name: Mi primer pipeline
on: push
jobs:
  calidad:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar el código
        uses: actions/checkout@v4
      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Instalar dependencias
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Correr los tests
        run: npm test
      - name: Build
        run: npm run build